CREATE DATABASE IF NOT EXISTS chettinad_thari_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chettinad_thari_db;

CREATE TABLE IF NOT EXISTS size_master (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  status TINYINT DEFAULT 1,
  createdon DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedon DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS color_master (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  status TINYINT DEFAULT 1,
  createdon DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedon DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
